apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      hostAliases:
      - ip: "192.168.10.10"
        hostnames:
        - "my.agrobank.uz"
      containers:
      - name: backend2
        image: k8s1.agrobank.uz:5000/backend2:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "750Mi"
            cpu: "1000m"
          requests:
            memory: "500Mi"
            cpu: "750m"
        env:                     # Environment variables passed to the container
          - name: REDIS_HOST
            value: "192.168.10.74"
          - name: REDIS_PORT
            value: "6379"
        volumeMounts:
        - name: nfs-volume
          mountPath: "/usr/src/app/files"
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: last
      imagePullSecrets:
      - name: secretkey2
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs2
  namespace: default
  labels:
    app: web
spec:
  selector:
    app: web
  ports:
  - port: 30003
    targetPort: 30003
  externalIPs:
  - 192.168.10.71