apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs2
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
