apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-history
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card
  template:
    metadata:
      labels:
        app: card
    spec:
      containers:
      - name: card-history
        image: k8s1.agrobank.uz:5000/card-history:latest
        imagePullPolicy: Always
        resources:
          limits:
 #           memory: "750Mi"
            cpu: 1000m
          requests:
 #           memory: "500Mi"
            cpu: 750m
      imagePullSecrets:
      - name: secretkey2        
---
apiVersion: v1
kind: Service
metadata:
  name: card-history
  namespace: default
spec:
  selector:
    app: card
  ports:
  - port: 3000
    targetPort: 3000
  externalIPs:
  - 192.168.10.71
