apiVersion: v1
kind: PersistentVolume
metadata:
  name: last
spec:
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: my-storage1
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.10.74
    path: /data/volumes/pv1
